### PR TITLE
Porting to Gtk+3[In progress], Port to Python 3, Port to CollabWrapper

### PR DESCRIPTION
**Pull request by JuiP**
Kindly Review the changes made. @quozl 
I am not sure how should I resolve the error-
"Import Error: No module named collabwrapper" due to the error I don't really know how should I test the changes and if it has more errors. Kindly help me resolve this, so I can continue making changes.

Testing on sugar desktop as vm:
Sugar: 0.116
Build: Debian GNU/ Linux 10 (buster)

Thanks

### CODE REVIEW

**Comment by quozl** [comment]
> I am not sure how should I resolve the error-
> "Import Error: No module named collabwrapper" due to the error I don't really know how should I test the changes and if it has more errors. Kindly help me resolve this, so I can continue making changes.

Tell me more about this error?  When does it occur?  From which change onwards does it occur?  Have you reviewed the CollabWrapper test activity?

> Kindly Review the changes made. @quozl

I'll not review changes until all problems are resolved, because there's a good chance you may have to revert changes or adjust the order or nature of the changes.  I'm happy to help with your work on any outstanding problems first.

**Comment by JuiP** [comment]
Thanks, I added the collabwrapper as a submodule, I got the following error- There does not seem to be an ImportError now, however, the error is the same error I faced while directly using git clone of bulletinboard and running it as sugar-activity.
Screenshot from 2020-03-17 09-36-35

**Comment by quozl** [comment]
Thanks.  Please use copy and paste into block text (```) in future, as images cannot be searched, take a long time to load, and are the wrong font size.

```log
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply:
```

It looks like you might be trying to run this as root?  That will be a separate D-Bus to the Sugar session, and so the bus won't contain what the session D-Bus will contain.

**Comment by JuiP** [comment]
Oops sorry, will use copy paste method next time. :)
Yes you are right there doesn't seem to be an issue if I'm not running this as root, however there are other errors, which I will try to fix myself first. I'll ask if I am stuck on an error I can't resolve.
Thanks a lot for helping :)

**Comment by JuiP** [comment]
@quozl I made more changes however, I don't know what this error is. Can you please help me proceed further?

```log
 according to signature 'sa{sv}sb': <class 'TypeError'>: Don't know which D-Bus type to use to encode type "NoneType"
1584516750.586783 ERROR root: Error saving activity object to datastore
Traceback (most recent call last):
  File "/usr/lib/python3.7/dist-packages/sugar3/activity/activity.py", line 1277, in _prepare_close
    self.save()
  File "/usr/lib/python3.7/dist-packages/sugar3/activity/activity.py", line 978, in save
    self.write_file(file_path)
  File "/usr/share/sugar/activities/bb.activity/BBoardActivity.py", line 606, in write_file
    self._save_descriptions_cb()
  File "/usr/share/sugar/activities/bb.activity/BBoardActivity.py", line 811, in _save_descriptions_cb
    error_handler=self.datastore_write_error_cb)
  File "/usr/lib/python3.7/dist-packages/sugar3/datastore/datastore.py", line 388, in write
    timeout=timeout)
  File "/usr/lib/python3.7/dist-packages/sugar3/datastore/datastore.py", line 337, in _update_ds_entry
    timeout=timeout)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 137, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 584, in call_async
    message.append(signature=signature, *args)
TypeError: Don't know which D-Bus type to use to encode type "NoneType"
```

The activity seems to work but the original functionality is not yet restored. I can't see the thumbnails in the thumbnail view. And exporting it as a pdf seems to take infinite time.

**Comment by quozl** [comment]
Thanks for the update.  For the traceback, check if `s.desc` is None.  If it is, that's the immediate cause.  Find where it is set, and make sure the code that sets it is doing the right thing.  Test with a debugger or print.

Communication with the datastore happens over D-Bus, so data has to conform to D-Bus types.  None is a Python concept that isn't automatically translated, hence the error.

Add to your checklist an end to end verification that any changed descriptions are changed in the Journal after the activity stops.  You've verified this works before porting, right?

**Comment by JuiP** [comment]
Even with the current changes the changed descriptions are reflected in Jornal details of the corresponding activity. 

- [ ] However, while using 'Stop' I get a message 
       Keep error: all changes will be lost. 
       Then choosing Stop anyway.

- [x] Irrespective of this, the change in description is reflected in the Journal.

- [x] On Erasing the Bulletin Board Activity from the Journal, the changed description remains 
       unaltered.



> Thanks for the update. For the traceback, check if `s.desc` is None. If it is, that's the immediate cause. Find where it is set, and make sure the code that sets it is doing the right thing. Test with a debugger or print.

Haven't really looked at resolving this error yet. Will get back to you soon.
Thanks :)

**Comment by quozl** [comment]
> However, while using 'Stop' I get a message Keep error: all changes will be lost.  Then choosing Stop anyway.

"Keep error" is a remnant of a design change from a decade ago that was disputed and debated heavily.  For a short time Sugar didn't save work unless instructed to do so.

However, for you, "Keep error" means the `write_file` method made an exception that was [handled here](https://github.com/sugarlabs/sugar-toolkit-gtk3/blob/master/src/sugar3/activity/activity.py#L977) rather than logged again, so all you should have to do is fix that exception.

> Haven't really looked at resolving this error yet. Will get back to you soon.

It relates to the keep error, so work on it when you can next.

**Comment by JuiP** [comment]
The Portfolio activity had the same user interface for earlier versions - checked on sugar 0.96
A lot of changes have been made to Portfolio activity since then; both feature changes and bug fixes.
Most of them necessarily need to be done in Bulletin Board too.
If similar changes need to be applied to Bulletin Board activity, then this might actually take up time. Any suggestions?

**Comment by quozl** [comment]
Your assessment seems likely to have approximated the reality, thanks.  I've no suggestions.

**Comment by JuiP** [comment]
I think this PR should be closed because:

- I do not plan on continuing work where I left
- This being my first PR, a lot of things are not right and I feel it's easier to start work on a fresh branch than continue and fix problems with this PR

Issues with this PR :
- I have not properly tested master before port to Gtk3 and python3.
- Port to python3 and port to Gtk3 are mixed up. Any regressions seen after porting will be difficult to identify as Gtk3 problem or python3 problem.

**Pull request closed without merging**
